services:
  ecommerce-app:
    build:
      context: .
    ports:
      - 5432:5432
    volumes:
      - ./target:/app/target
    working_dir: /app
    command: mvn clean install -DskipTests
    environment:
      - DATABASE_USERNAME=store
      - DATABASE_PASSWORD=5FQxvrDR4KSm3v7nWvCmisS476O4kYYO



#services:
#  postgres:
#    container_name: test-store
#    image: postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=admin123
#      - POSTGRES_DB=store
#    ports:
#      - 5432:5432