version: '3'
services:
  ecommerce-app:
    build:
      context: .
    ports:
      - 5432:5432
    volumes:
      - ./target:/app/target
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=store

#services:
#  postgres:
#    container_name: test-store
#    image: postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=admin123
#      - POSTGRES_DB=store
#    ports:
#      - 5432:5432