version: '3.8'

services:
  postgres:
    container_name: store
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=store
    ports:
      - 5432:5432